plugins {
    id 'java-library'
    id 'maven-publish'
    alias(libs.plugins.teavm)
}

def ENV = System.getenv()
version = version + (ENV.GITHUB_ACTIONS ? "" : "+local")

repositories {
    mavenCentral()
}

sourceSets {
    wasm
    dummy1
    dummy2
    dummy3
    dummy4
}

dependencies {
    api libs.asm
    api libs.asm.commons
    api libs.asm.util
    api libs.mapping.io
    api libs.mapping.io.extras
    wasmImplementation sourceSets.main.output
    wasmImplementation libs.teavm.jso
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

tasks.register('dummy1Jar', Jar) {
    from sourceSets.dummy1.output
    archiveBaseName = 'dummy1'
    archiveVersion = ''
    archiveClassifier = ''
}

tasks.register('dummy2Jar', Jar) {
    from sourceSets.dummy2.output
    archiveBaseName = 'dummy2'
    archiveVersion = ''
    archiveClassifier = ''
}

tasks.register('dummy3Jar', Jar) {
    from sourceSets.dummy3.output
    archiveBaseName = 'dummy3'
    archiveVersion = ''
    archiveClassifier = ''
}

tasks.register('dummy4Jar', Jar) {
    from sourceSets.dummy4.output
    archiveBaseName = 'dummy4'
    archiveVersion = ''
    archiveClassifier = ''
}

teavm {
    all {
        mainClass = "mcsrc.WasmInterface"
    }
    js {
        moduleType = org.teavm.gradle.api.JSModuleType.ES2015
        optimization = org.teavm.gradle.api.OptimizationLevel.AGGRESSIVE
    }
    wasmGC {
        addedToWebApp = true
        modularRuntime = true
//        obfuscated = false
        optimization = org.teavm.gradle.api.OptimizationLevel.AGGRESSIVE
    }
}

['generateJavaScript', 'generateWasmGC'].each {
    tasks.named(it) {
        classpath.from sourceSets.wasm.runtimeClasspath
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifactId = 'core'
            from components.java
        }
    }
    repositories {
        if (ENV.MAVEN_URL) {
            maven {
                url ENV.MAVEN_URL
                credentials {
                    username ENV.MAVEN_USERNAME
                    password ENV.MAVEN_PASSWORD
                }
            }
        }
    }
}

tasks.named("build") {
    dependsOn tasks.generateJavaScript
    dependsOn tasks.generateWasmGC
    dependsOn tasks.copyWasmGCRuntime
    dependsOn tasks.dummy1Jar
    dependsOn tasks.dummy2Jar
    dependsOn tasks.dummy3Jar
    dependsOn tasks.dummy4Jar
}
