name: Release
on: [workflow_dispatch] # Manual trigger
jobs:
  build:
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v5
      - run: ./gradlew build publish --stacktrace
        working-directory: java
        env:
          MAVEN_URL: ${{ secrets.MAVEN_URL }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}